testname: Network Test Valid 1
email: john.doe@email.com
config:

  - networkname: google
    host: google.com
    port: 80
    path:
    proto: http
    capturebody: false

  - networkname: amazon
    host: amazon.com
    port: 443
    path:
    proto: https
    capturebody: true
